//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_TUT.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public Nullable<int> PostWeight { get; set; }
        public string PostName { get; set; }
        public Nullable<int> catId { get; set; }
        [NotMapped]
        public string catName { get; set; }
    }
}
